const CHARACTERS = {
  ned: {
    name: "Ned Stark",
    title: "Lord of Winterfell",
    house: "Stark",
    image: "images/ned.jpg",
  },
  catelyn: {
    name: "Catelyn Stark",
    title: "Lady of Winterfell",
    house: "Stark",
    image: "images/catelyn.jpg",
  },
  robb: {
    name: "Robb Stark",
    title: "King in the North",
    house: "Stark",
    image: "images/robb.jpg",
  },
  sansa: {
    name: "Sansa Stark",
    title: "Lady of Winterfell",
    house: "Stark",
    image: "images/sansa.jpg",
  },
  arya: {
    name: "Arya Stark",
    title: "Princess of Winterfell",
    house: "Stark",
    image: "images/arya.jpg",
  },
  bran: {
    name: "Bran Stark",
    title: "Three-Eyed Raven",
    house: "Stark",
    image: "images/bran.jpg",
  },
  rickon: {
    name: "Rickon Stark",
    title: "Prince of Winterfell",
    house: "Stark",
    image: "images/rickon.jpg",
  },
  jon: {
    name: "Jon Snow",
    title: "Lord Commander",
    house: "Stark",
    image: "images/jon.jpg",
  },
  theon: {
    name: "Theon Greyjoy",
    title: "Prince of the Iron Islands",
    house: "Greyjoy",
    image: "images/theon.jpg",
  },
  daenerys: {
    name: "Daenerys Targaryen",
    title: "Mother of Dragons",
    house: "Targaryen",
    image: "images/daenerys.jpg",
  },
  drogo: {
    name: "Khal Drogo",
    title: "Khal of the Great Grass Sea",
    house: "Dothraki",
    image: "images/drogo.jpg",
  },
  viserys: {
    name: "Viserys Targaryen",
    title: "The Beggar King",
    house: "Targaryen",
    image: "images/viserys.jpg",
  },
  tyrion: {
    name: "Tyrion Lannister",
    title: "Hand of the Queen",
    house: "Lannister",
    image: "images/tyrion.jpg",
  },
  jaime: {
    name: "Jaime Lannister",
    title: "Kingslayer",
    house: "Lannister",
    image: "images/jaime.jpg",
  },
  cersei: {
    name: "Cersei Lannister",
    title: "Queen of the Seven Kingdoms",
    house: "Lannister",
    image: "images/cersei.jpg",
  },
  joffrey: {
    name: "Joffrey Baratheon",
    title: "King of the Andals",
    house: "Baratheon",
    image: "images/joffrey.jpg",
  },
  robert: {
    name: "Robert Baratheon",
    title: "King of the Seven Kingdoms",
    house: "Baratheon",
    image: "images/robert.jpg",
  },
  tywin: {
    name: "Tywin Lannister",
    title: "Hand of the King",
    house: "Lannister",
    image: "images/tywin.jpg",
  },
  hound: {
    name: "Sandor Clegane",
    title: "The Hound",
    house: "Clegane",
    image: "images/hound.jpg",
  },
  littlefinger: {
    name: "Petyr Baelish",
    title: "Littlefinger",
    house: "Baelish",
    image: "images/littlefinger.jpg",
  },
  varys: {
    name: "Varys",
    title: "Master of Whisperers",
    house: "None",
    image: "images/varys.jpg",
  },
  jorah: {
    name: "Jorah Mormont",
    title: "Advisor to the Queen",
    house: "Mormont",
    image: "images/jorah.jpg",
  },
  sam: {
    name: "Samwell Tarly",
    title: "Maester of the Citadel",
    house: "Tarly",
    image: "images/sam.jpg",
  },
  bronn: {
    name: "Bronn",
    title: "Sellsword",
    house: "None",
    image: "images/bronn.jpg",
  },
  jeor: {
    name: "Jeor Mormont",
    title: "Lord Commander",
    house: "Mormont",
    image: "images/jeor.jpg",
  },
  stannis: {
    name: "Stannis Baratheon",
    title: "Lord of Dragonstone",
    house: "Baratheon",
    image: "images/stannis.jpg",
  },
  melisandre: {
    name: "Melisandre",
    title: "The Red Woman",
    house: "R'hllor",
    image: "images/melisandre.jpg",
  },
  davos: {
    name: "Davos Seaworth",
    title: "Onion Knight",
    house: "Seaworth",
    image: "images/davos.png",
  },
  margaery: {
    name: "Margaery Tyrell",
    title: "Queen Consort",
    house: "Tyrell",
    image: "images/margaery.jpg",
  },
  ygritte: {
    name: "Ygritte",
    title: "Spearwife",
    house: "Free Folk",
    image: "images/ygritte.jpg",
  },
  brienne: {
    name: "Brienne of Tarth",
    title: "Knight of the Seven Kingdoms",
    house: "Tarth",
    image: "images/brienne.jpg",
  },
  jaqen: {
    name: "Jaqen H'ghar",
    title: "A Man of Braavos",
    house: "Faceless Men",
    image: "images/jaqen.jpg",
  },
  talisa: {
    name: "Talisa Stark",
    title: "Queen in the North",
    house: "Stark",
    image: "images/talisa.jpg",
  },
  yara: {
    name: "Yara Greyjoy",
    title: "Lady of the Iron Islands",
    house: "Greyjoy",
    image: "images/yara.jpg",
  },
  gendry: {
    name: "Gendry",
    title: "Lord of Storm's End",
    house: "Baratheon",
    image: "images/gendry.jpg",
  },
  gilly: {
    name: "Gilly",
    title: "Wildling",
    house: "Free Folk",
    image: "images/gilly.jpg",
  },
  missandei: {
    name: "Missandei",
    title: "Advisor to the Queen",
    house: "Naath",
    image: "images/missandei.jpg",
  },
  greyWorm: {
    name: "Grey Worm",
    title: "Commander of the Unsullied",
    house: "Unsullied",
    image: "images/greyWorm.jpg",
  },
  tormund: {
    name: "Tormund Giantsbane",
    title: "Free Folk Leader",
    house: "Free Folk",
    image: "images/tormund.jpg",
  },
  hodor: {
    name: "Hodor",
    title: "Protector of Bran",
    house: "Stark",
    image: "images/hodor.jpg",
  },
  olenna: {
    name: "Olenna Tyrell",
    title: "Queen of Thorns",
    house: "Tyrell",
    image: "images/olenna.jpg",
  },
  daario: {
    name: "Daario Naharis",
    title: "Commander of the Second Sons",
    house: "Second Sons",
    image: "images/daario.jpg",
  },
  shae: {
    name: "Shae",
    title: "Handmaiden",
    house: "None",
    image: "images/shae.jpg",
  },
  ramsay: {
    name: "Ramsay Bolton",
    title: "Lord of Winterfell",
    house: "Bolton",
    image: "images/ramsay.jpg",
  },
  roose: {
    name: "Roose Bolton",
    title: "Warden of the North",
    house: "Bolton",
    image: "images/roose.jpg",
  },
  oberyn: {
    name: "Oberyn Martell",
    title: "The Red Viper",
    house: "Martell",
    image: "images/oberyn.jpg",
  },
  ellaria: {
    name: "Ellaria Sand",
    title: "Paramour of Oberyn",
    house: "Martell",
    image: "images/ellaria.jpg",
  },
  tommen: {
    name: "Tommen Baratheon",
    title: "King of the Seven Kingdoms",
    house: "Baratheon",
    image: "images/tommen.jpg",
  },
  highSparrow: {
    name: "The High Sparrow",
    title: "High Septon",
    house: "Faith",
    image: "images/highSparrow.jpg",
  },
  euron: {
    name: "Euron Greyjoy",
    title: "King of the Iron Islands",
    house: "Greyjoy",
    image: "images/euron.jpg",
  },
  qyburn: {
    name: "Qyburn",
    title: "Master of Whisperers",
    house: "None",
    image: "images/qyburn.jpg",
  },
  pycelle: {
    name: "Grand Maester Pycelle",
    title: "Grand Maester",
    house: "None",
    image: "images/pycelle.jpg",
  },
  lysa: {
    name: "Lysa Arryn",
    title: "Lady of the Eyrie",
    house: "Arryn",
    image: "images/lysa.jpg",
  },
  robin: {
    name: "Robin Arryn",
    title: "Lord of the Eyrie",
    house: "Arryn",
    image: "images/robin.png",
  },
  renly: {
    name: "Renly Baratheon",
    title: "Lord of Storm's End",
    house: "Baratheon",
    image: "images/renly.png",
  },
  loras: {
    name: "Loras Tyrell",
    title: "Knight of the Flowers",
    house: "Tyrell",
    image: "images/loras.png",
  },
  barristan: {
    name: "Barristan Selmy",
    title: "Lord Commander of the Kingsguard",
    house: "None",
    image: "images/barristan.jpg",
  },
  benjen: {
    name: "Benjen Stark",
    title: "First Ranger",
    house: "Stark",
    image: "images/benjen.png",
  },
  syrio: {
    name: "Syrio Forel",
    title: "First Sword of Braavos",
    house: "None",
    image: "images/syrio.png",
  },
  luwin: {
    name: "Maester Luwin",
    title: "Maester of Winterfell",
    house: "Stark",
    image: "images/luwin.jpg",
  },
  osha: {
    name: "Osha",
    title: "Wildling",
    house: "Free Folk",
    image: "images/osha.jpg",
  },
  alliser: {
    name: "Alliser Thorne",
    title: "First Ranger",
    house: "Night's Watch",
    image: "images/alliser.jpg",
  },
  aemon: {
    name: "Maester Aemon",
    title: "Maester of Castle Black",
    house: "Night's Watch",
    image: "images/aemon.png",
  },
  myrcella: {
    name: "Myrcella Baratheon",
    title: "Princess",
    house: "Baratheon",
    image: "images/myrcella.jpg",
  },
  podrick: {
    name: "Podrick Payne",
    title: "Squire",
    house: "None",
    image: "images/podrick.png",
  },
  edmure: {
    name: "Edmure Tully",
    title: "Lord of Riverrun",
    house: "Tully",
    image: "images/edmure.png",
  },
  blackfish: {
    name: "Brynden Tully",
    title: "The Blackfish",
    house: "Tully",
    image: "images/blackfish.png",
  },
  walder: {
    name: "Walder Frey",
    title: "Lord of the Crossing",
    house: "Frey",
    image: "images/walder.jpg",
  },
  mance: {
    name: "Mance Rayder",
    title: "King-Beyond-the-Wall",
    house: "Free Folk",
    image: "images/mance.jpg",
  },
  shireen: {
    name: "Shireen Baratheon",
    title: "Princess of Dragonstone",
    house: "Baratheon",
    image: "images/shireen.jpg",
  },
  selyse: {
    name: "Selyse Baratheon",
    title: "Queen of Dragonstone",
    house: "Baratheon",
    image: "images/selyse.png",
  },
  nightKing: {
    name: "The Night King",
    title: "Lord of the White Walkers",
    house: "White Walkers",
    image: "images/nightKing.jpg",
  },
  meera: {
    name: "Meera Reed",
    title: "Of House Reed",
    house: "Stark",
    image: "images/meera.png",
  },
  jojen: {
    name: "Jojen Reed",
    title: "Of House Reed",
    house: "Stark",
    image: "images/jojen.jpg",
  },
  lyanna: {
    name: "Lyanna Mormont",
    title: "Lady of Bear Island",
    house: "Mormont",
    image: "images/lyanna.jpg",
  },
  beric: {
    name: "Beric Dondarrion",
    title: "Lord of Blackhaven",
    house: "None",
    image: "images/beric.png",
  },
  thoros: {
    name: "Thoros of Myr",
    title: "Red Priest",
    house: "R'hllor",
    image: "images/thoros.png",
  },
  randyll: {
    name: "Randyll Tarly",
    title: "Lord of Horn Hill",
    house: "Tarly",
    image: "images/randyll.png",
  },
  kevan: {
    name: "Kevan Lannister",
    title: "Hand of the King",
    house: "Lannister",
    image: "images/kevan.png",
  },
  lancel: {
    name: "Lancel Lannister",
    title: "A Lannister of Casterly Rock",
    house: "Lannister",
    image: "images/lancel.jpg",
  },
  doran: {
    name: "Doran Martell",
    title: "Prince of Dorne",
    house: "Martell",
    image: "images/doran.png",
  },
  edd: {
    name: "Eddison Tollett",
    title: "Dolorous Edd",
    house: "Night's Watch",
    image: "images/edd.png",
  },
  yoren: {
    name: "Yoren",
    title: "Wandering Crow",
    house: "Night's Watch",
    image: "images/yoren.jpg",
  },
  janos: {
    name: "Janos Slynt",
    title: "Lord of Harrenhal",
    house: "None",
    image: "images/janos.png",
  },
  hotPie: {
    name: "Hot Pie",
    title: "Baker",
    house: "None",
    image: "images/hotPie.png",
  },
  hizdahr: {
    name: "Hizdahr zo Loraq",
    title: "King Consort of Meereen",
    house: "None",
    image: "images/hizdahr.jpg",
  },
  yohn: {
    name: "Yohn Royce",
    title: "Lord of Runestone",
    house: "Arryn",
    image: "images/yohn.png",
  },
  olly: {
    name: "Olly",
    title: "Steward of the Night's Watch",
    house: "Night's Watch",
    image: "images/olly.png",
  },
};

const SEASONS = [
  {
    number: 1,
    title: "Winter Is Coming",
    year: "2011",
    blurb: "The Starks of Winterfell, the Lannisters of King's Landing, and a Targaryen across the Narrow Sea begin a story that will consume the Seven Kingdoms.",
    characters: [
      "ned",
      "catelyn",
      "robb",
      "sansa",
      "arya",
      "bran",
      "rickon",
      "jon",
      "lysa",
      "robin",
      "daenerys",
      "drogo",
      "viserys",
      "tyrion",
      "jaime",
      "cersei",
      "joffrey",
      "myrcella",
      "robert",
      "renly",
      "loras",
      "theon",
      "littlefinger",
      "varys",
      "jorah",
      "barristan",
      "hound",
      "tywin",
      "kevan",
      "lancel",
      "pycelle",
      "shae",
      "bronn",
      "sam",
      "jeor",
      "benjen",
      "alliser",
      "aemon",
      "yoren",
      "janos",
      "syrio",
      "luwin",
      "osha",
      "walder",
    ],
  },
  {
    number: 2,
    title: "The North Remembers",
    year: "2012",
    blurb: "Five kings claim the Iron Throne. War spreads from Winterfell to the Blackwater, while Daenerys gathers strength in Qarth.",
    characters: [
      "tyrion",
      "cersei",
      "jaime",
      "joffrey",
      "myrcella",
      "tywin",
      "kevan",
      "lancel",
      "pycelle",
      "shae",
      "bronn",
      "robb",
      "catelyn",
      "sansa",
      "arya",
      "bran",
      "rickon",
      "jon",
      "daenerys",
      "theon",
      "stannis",
      "renly",
      "melisandre",
      "davos",
      "margaery",
      "loras",
      "brienne",
      "ygritte",
      "littlefinger",
      "varys",
      "jorah",
      "barristan",
      "hound",
      "jaqen",
      "talisa",
      "yara",
      "sam",
      "gilly",
      "jeor",
      "alliser",
      "aemon",
      "edd",
      "yoren",
      "janos",
      "podrick",
      "luwin",
      "osha",
      "hotPie",
    ],
  },
  {
    number: 3,
    title: "Valar Dohaeris",
    year: "2013",
    blurb: "All men must serve. Robb's campaign reaches its grim turning point, Jon walks among the Free Folk, and Daenerys buys an army.",
    characters: [
      "robb",
      "catelyn",
      "talisa",
      "edmure",
      "blackfish",
      "walder",
      "sansa",
      "arya",
      "bran",
      "rickon",
      "hodor",
      "osha",
      "meera",
      "jojen",
      "jon",
      "ygritte",
      "tormund",
      "mance",
      "daenerys",
      "missandei",
      "greyWorm",
      "jorah",
      "barristan",
      "tyrion",
      "jaime",
      "brienne",
      "podrick",
      "cersei",
      "joffrey",
      "margaery",
      "loras",
      "olenna",
      "tywin",
      "shae",
      "pycelle",
      "bronn",
      "theon",
      "ramsay",
      "hound",
      "gendry",
      "hotPie",
      "beric",
      "thoros",
      "sam",
      "gilly",
      "aemon",
      "alliser",
      "edd",
      "shireen",
      "selyse",
    ],
  },
  {
    number: 4,
    title: "Two Swords",
    year: "2014",
    blurb: "A royal wedding in King's Landing. The Wall faces its greatest assault. In the east, Daenerys rules Meereen — and trials for the accused begin.",
    characters: [
      "tyrion",
      "jaime",
      "cersei",
      "joffrey",
      "tommen",
      "myrcella",
      "tywin",
      "oberyn",
      "ellaria",
      "sansa",
      "lysa",
      "robin",
      "yohn",
      "littlefinger",
      "arya",
      "hound",
      "hotPie",
      "bran",
      "hodor",
      "meera",
      "jojen",
      "jon",
      "sam",
      "gilly",
      "aemon",
      "alliser",
      "janos",
      "edd",
      "olly",
      "tormund",
      "ygritte",
      "mance",
      "nightKing",
      "daenerys",
      "jorah",
      "barristan",
      "missandei",
      "greyWorm",
      "daario",
      "hizdahr",
      "stannis",
      "davos",
      "melisandre",
      "selyse",
      "shireen",
      "brienne",
      "podrick",
      "varys",
      "shae",
      "pycelle",
      "bronn",
      "margaery",
      "loras",
      "olenna",
    ],
  },
  {
    number: 5,
    title: "The Wars to Come",
    year: "2015",
    blurb: "Faith militant rise in King's Landing. Jon Snow is chosen at the Wall. Daenerys's rule in Meereen is tested. Sansa returns north.",
    characters: [
      "cersei",
      "jaime",
      "tommen",
      "margaery",
      "loras",
      "olenna",
      "highSparrow",
      "lancel",
      "kevan",
      "pycelle",
      "tyrion",
      "varys",
      "daenerys",
      "jorah",
      "barristan",
      "missandei",
      "greyWorm",
      "daario",
      "hizdahr",
      "jon",
      "sam",
      "gilly",
      "aemon",
      "alliser",
      "edd",
      "olly",
      "janos",
      "stannis",
      "melisandre",
      "davos",
      "selyse",
      "shireen",
      "sansa",
      "littlefinger",
      "robin",
      "yohn",
      "ramsay",
      "roose",
      "theon",
      "arya",
      "jaqen",
      "brienne",
      "podrick",
      "tormund",
      "mance",
      "nightKing",
      "bronn",
      "ellaria",
      "doran",
      "myrcella",
    ],
  },
  {
    number: 6,
    title: "The Red Woman",
    year: "2016",
    blurb: "The dead do not stay dead. Alliances shatter in King's Landing, and the North remembers who their king should be.",
    characters: [
      "jon",
      "sansa",
      "davos",
      "melisandre",
      "tormund",
      "brienne",
      "podrick",
      "theon",
      "ramsay",
      "rickon",
      "osha",
      "lyanna",
      "yohn",
      "benjen",
      "daenerys",
      "tyrion",
      "varys",
      "missandei",
      "greyWorm",
      "cersei",
      "jaime",
      "tommen",
      "margaery",
      "loras",
      "highSparrow",
      "kevan",
      "lancel",
      "olenna",
      "pycelle",
      "qyburn",
      "arya",
      "bran",
      "hodor",
      "meera",
      "sam",
      "gilly",
      "alliser",
      "edd",
      "olly",
      "euron",
      "yara",
      "littlefinger",
      "walder",
      "edmure",
      "blackfish",
      "beric",
      "thoros",
      "hound",
      "nightKing",
      "randyll",
      "bronn",
    ],
  },
  {
    number: 7,
    title: "Dragonstone",
    year: "2017",
    blurb: "Ice and fire finally meet. Daenerys sails west, the Great War looms, and old houses choose their last loyalties.",
    characters: [
      "daenerys",
      "jon",
      "tyrion",
      "cersei",
      "jaime",
      "sansa",
      "arya",
      "bran",
      "meera",
      "theon",
      "yara",
      "euron",
      "varys",
      "jorah",
      "missandei",
      "greyWorm",
      "davos",
      "brienne",
      "podrick",
      "hound",
      "gendry",
      "hotPie",
      "tormund",
      "sam",
      "gilly",
      "littlefinger",
      "olenna",
      "bronn",
      "qyburn",
      "melisandre",
      "beric",
      "thoros",
      "lyanna",
      "yohn",
      "edd",
      "nightKing",
      "randyll",
    ],
  },
  {
    number: 8,
    title: "The Iron Throne",
    year: "2019",
    blurb: "The Great War comes to Winterfell. The last claim to the Iron Throne is decided — and the song of ice and fire ends.",
    characters: [
      "daenerys",
      "jon",
      "sansa",
      "arya",
      "bran",
      "tyrion",
      "cersei",
      "jaime",
      "theon",
      "varys",
      "jorah",
      "missandei",
      "greyWorm",
      "davos",
      "brienne",
      "podrick",
      "hound",
      "gendry",
      "tormund",
      "sam",
      "gilly",
      "euron",
      "bronn",
      "qyburn",
      "yara",
      "lyanna",
      "beric",
      "edd",
      "yohn",
      "robin",
      "edmure",
      "nightKing",
    ],
  },
];
