const CHARACTERS = {
  ned: {
    name: "Ned Stark",
    title: "Lord of Winterfell",
    house: "Stark",
    image: "https://thronesapi.com/assets/images/ned-stark.jpg",
  },
  catelyn: {
    name: "Catelyn Stark",
    title: "Lady of Winterfell",
    house: "Stark",
    image: "https://thronesapi.com/assets/images/catelyn-stark.jpg",
  },
  robb: {
    name: "Robb Stark",
    title: "King in the North",
    house: "Stark",
    image: "https://thronesapi.com/assets/images/robb-stark.jpg",
  },
  sansa: {
    name: "Sansa Stark",
    title: "Lady of Winterfell",
    house: "Stark",
    image: "https://thronesapi.com/assets/images/sansa-stark.jpeg",
  },
  arya: {
    name: "Arya Stark",
    title: "Princess of Winterfell",
    house: "Stark",
    image: "https://thronesapi.com/assets/images/arya-stark.jpg",
  },
  bran: {
    name: "Bran Stark",
    title: "Three-Eyed Raven",
    house: "Stark",
    image: "https://thronesapi.com/assets/images/bran-stark.jpg",
  },
  rickon: {
    name: "Rickon Stark",
    title: "Prince of Winterfell",
    house: "Stark",
    image: "https://thronesapi.com/assets/images/rickon.jpg",
  },
  jon: {
    name: "Jon Snow",
    title: "Lord Commander",
    house: "Stark",
    image: "https://thronesapi.com/assets/images/jon-snow.jpg",
  },
  theon: {
    name: "Theon Greyjoy",
    title: "Prince of the Iron Islands",
    house: "Greyjoy",
    image: "https://thronesapi.com/assets/images/theon.jpg",
  },
  daenerys: {
    name: "Daenerys Targaryen",
    title: "Mother of Dragons",
    house: "Targaryen",
    image: "https://thronesapi.com/assets/images/daenerys.jpg",
  },
  drogo: {
    name: "Khal Drogo",
    title: "Khal of the Great Grass Sea",
    house: "Dothraki",
    image: "https://thronesapi.com/assets/images/khal-drogo.jpg",
  },
  viserys: {
    name: "Viserys Targaryen",
    title: "The Beggar King",
    house: "Targaryen",
    image: "https://thronesapi.com/assets/images/viserys-targaryan.jpg",
  },
  tyrion: {
    name: "Tyrion Lannister",
    title: "Hand of the Queen",
    house: "Lannister",
    image: "https://thronesapi.com/assets/images/tyrion-lannister.jpg",
  },
  jaime: {
    name: "Jaime Lannister",
    title: "Kingslayer",
    house: "Lannister",
    image: "https://thronesapi.com/assets/images/jaime-lannister.jpg",
  },
  cersei: {
    name: "Cersei Lannister",
    title: "Queen of the Seven Kingdoms",
    house: "Lannister",
    image: "https://thronesapi.com/assets/images/cersei.jpg",
  },
  joffrey: {
    name: "Joffrey Baratheon",
    title: "King of the Andals",
    house: "Baratheon",
    image: "https://thronesapi.com/assets/images/joffrey.jpg",
  },
  robert: {
    name: "Robert Baratheon",
    title: "King of the Seven Kingdoms",
    house: "Baratheon",
    image: "https://thronesapi.com/assets/images/king-robert.jpg",
  },
  tywin: {
    name: "Tywin Lannister",
    title: "Hand of the King",
    house: "Lannister",
    image: "https://thronesapi.com/assets/images/tywin-lannister.jpg",
  },
  hound: {
    name: "Sandor Clegane",
    title: "The Hound",
    house: "Clegane",
    image: "https://thronesapi.com/assets/images/the-hound.jpg",
  },
  littlefinger: {
    name: "Petyr Baelish",
    title: "Littlefinger",
    house: "Baelish",
    image: "https://thronesapi.com/assets/images/littlefinger.jpg",
  },
  varys: {
    name: "Varys",
    title: "Master of Whisperers",
    house: "None",
    image: "https://thronesapi.com/assets/images/varys.jpg",
  },
  jorah: {
    name: "Jorah Mormont",
    title: "Advisor to the Queen",
    house: "Mormont",
    image: "https://thronesapi.com/assets/images/jorah-mormont.jpg",
  },
  sam: {
    name: "Samwell Tarly",
    title: "Maester of the Citadel",
    house: "Tarly",
    image: "https://thronesapi.com/assets/images/sam.jpg",
  },
  bronn: {
    name: "Bronn",
    title: "Sellsword",
    house: "None",
    image: "https://thronesapi.com/assets/images/bronn.jpg",
  },
  jeor: {
    name: "Jeor Mormont",
    title: "Lord Commander",
    house: "Mormont",
    image: "https://thronesapi.com/assets/images/lord-commander-mormont.jpg",
  },
  stannis: {
    name: "Stannis Baratheon",
    title: "Lord of Dragonstone",
    house: "Baratheon",
    image: "https://thronesapi.com/assets/images/stannis.jpg",
  },
  melisandre: {
    name: "Melisandre",
    title: "The Red Woman",
    house: "R'hllor",
    image: "https://thronesapi.com/assets/images/melisandre.jpg",
  },
  davos: {
    name: "Davos Seaworth",
    title: "Onion Knight",
    house: "Seaworth",
    image: "https://thronesapi.com/assets/images/davos-seaworth.png",
  },
  margaery: {
    name: "Margaery Tyrell",
    title: "Queen Consort",
    house: "Tyrell",
    image: "https://thronesapi.com/assets/images/margaery-tyrell.jpg",
  },
  ygritte: {
    name: "Ygritte",
    title: "Spearwife",
    house: "Free Folk",
    image: "https://thronesapi.com/assets/images/ygritte.jpg",
  },
  brienne: {
    name: "Brienne of Tarth",
    title: "Knight of the Seven Kingdoms",
    house: "Tarth",
    image: "https://thronesapi.com/assets/images/brienne-tarth.jpeg",
  },
  jaqen: {
    name: "Jaqen H'ghar",
    title: "A Man of Braavos",
    house: "Faceless Men",
    image: "https://thronesapi.com/assets/images/jaqen-hghar.jpg",
  },
  talisa: {
    name: "Talisa Stark",
    title: "Queen in the North",
    house: "Stark",
    image: "https://thronesapi.com/assets/images/talisa-stark.jpg",
  },
  yara: {
    name: "Yara Greyjoy",
    title: "Lady of the Iron Islands",
    house: "Greyjoy",
    image: "https://thronesapi.com/assets/images/yara-greyjoy.jpg",
  },
  gendry: {
    name: "Gendry",
    title: "Lord of Storm's End",
    house: "Baratheon",
    image: "https://thronesapi.com/assets/images/gendry.jpg",
  },
  gilly: {
    name: "Gilly",
    title: "Wildling",
    house: "Free Folk",
    image: "https://thronesapi.com/assets/images/gilly.jpg",
  },
  missandei: {
    name: "Missandei",
    title: "Advisor to the Queen",
    house: "Naath",
    image: "https://thronesapi.com/assets/images/missandei.jpeg",
  },
  greyWorm: {
    name: "Grey Worm",
    title: "Commander of the Unsullied",
    house: "Unsullied",
    image: "https://thronesapi.com/assets/images/greyworm.jpg",
  },
  tormund: {
    name: "Tormund Giantsbane",
    title: "Free Folk Leader",
    house: "Free Folk",
    image: "https://thronesapi.com/assets/images/tormund-giantsbane.jpg",
  },
  hodor: {
    name: "Hodor",
    title: "Protector of Bran",
    house: "Stark",
    image: "https://thronesapi.com/assets/images/hodor.jpg",
  },
  olenna: {
    name: "Olenna Tyrell",
    title: "Queen of Thorns",
    house: "Tyrell",
    image: "https://thronesapi.com/assets/images/olenna-tyrell.jpg",
  },
  daario: {
    name: "Daario Naharis",
    title: "Commander of the Second Sons",
    house: "Second Sons",
    image: "https://thronesapi.com/assets/images/daario.jpg",
  },
  shae: {
    name: "Shae",
    title: "Handmaiden",
    house: "None",
    image: "https://thronesapi.com/assets/images/shae.jpg",
  },
  ramsay: {
    name: "Ramsay Bolton",
    title: "Lord of Winterfell",
    house: "Bolton",
    image: "https://thronesapi.com/assets/images/ramsey-bolton.jpg",
  },
  roose: {
    name: "Roose Bolton",
    title: "Warden of the North",
    house: "Bolton",
    image: "https://thronesapi.com/assets/images/roose-bolton.jpg",
  },
  oberyn: {
    name: "Oberyn Martell",
    title: "The Red Viper",
    house: "Martell",
    image: "https://thronesapi.com/assets/images/red-viper.jpg",
  },
  ellaria: {
    name: "Ellaria Sand",
    title: "Paramour of Oberyn",
    house: "Martell",
    image: "https://thronesapi.com/assets/images/ellaria-sand.jpg",
  },
  tommen: {
    name: "Tommen Baratheon",
    title: "King of the Seven Kingdoms",
    house: "Baratheon",
    image: "https://thronesapi.com/assets/images/tommen.jpg",
  },
  highSparrow: {
    name: "The High Sparrow",
    title: "High Septon",
    house: "Faith",
    image: "https://thronesapi.com/assets/images/the-high-sparrow.jpg",
  },
  euron: {
    name: "Euron Greyjoy",
    title: "King of the Iron Islands",
    house: "Greyjoy",
    image: "https://thronesapi.com/assets/images/euron-greyjoy.jpg",
  },
  qyburn: {
    name: "Qyburn",
    title: "Master of Whisperers",
    house: "None",
    image: "https://thronesapi.com/assets/images/qyburn.jpg",
  },
  pycelle: {
    name: "Grand Maester Pycelle",
    title: "Grand Maester",
    house: "None",
    image: "https://thronesapi.com/assets/images/pycelle.jpg",
  },
};

const SEASONS = [
  {
    number: 1,
    title: "Winter Is Coming",
    year: "2011",
    blurb: "The Starks of Winterfell, the Lannisters of King's Landing, and a Targaryen across the Narrow Sea begin a story that will consume the Seven Kingdoms.",
    characters: [
      "ned",
      "catelyn",
      "robb",
      "sansa",
      "arya",
      "bran",
      "jon",
      "daenerys",
      "drogo",
      "viserys",
      "tyrion",
      "jaime",
      "cersei",
      "joffrey",
      "robert",
      "theon",
      "littlefinger",
      "varys",
      "jorah",
      "hound",
      "tywin",
      "sam",
      "bronn",
      "jeor",
    ],
  },
  {
    number: 2,
    title: "The North Remembers",
    year: "2012",
    blurb: "Five kings claim the Iron Throne. War spreads from Winterfell to the Blackwater, while Daenerys gathers strength in Qarth.",
    characters: [
      "tyrion",
      "cersei",
      "jaime",
      "joffrey",
      "tywin",
      "robb",
      "catelyn",
      "sansa",
      "arya",
      "bran",
      "jon",
      "daenerys",
      "theon",
      "stannis",
      "melisandre",
      "davos",
      "margaery",
      "brienne",
      "ygritte",
      "littlefinger",
      "varys",
      "jorah",
      "hound",
      "jaqen",
      "talisa",
      "yara",
      "sam",
      "gilly",
    ],
  },
  {
    number: 3,
    title: "Valar Dohaeris",
    year: "2013",
    blurb: "All men must serve. Robb's campaign reaches its grim turning point, Jon walks among the Free Folk, and Daenerys buys an army.",
    characters: [
      "robb",
      "catelyn",
      "talisa",
      "sansa",
      "arya",
      "bran",
      "hodor",
      "jon",
      "ygritte",
      "tormund",
      "daenerys",
      "missandei",
      "greyWorm",
      "jorah",
      "tyrion",
      "jaime",
      "brienne",
      "cersei",
      "joffrey",
      "margaery",
      "olenna",
      "tywin",
      "theon",
      "ramsay",
      "hound",
      "gendry",
      "sam",
      "gilly",
    ],
  },
  {
    number: 4,
    title: "Two Swords",
    year: "2014",
    blurb: "A royal wedding in King's Landing. The Wall faces its greatest assault. In the east, Daenerys rules Meereen — and trials for the accused begin.",
    characters: [
      "tyrion",
      "jaime",
      "cersei",
      "joffrey",
      "tommen",
      "tywin",
      "oberyn",
      "ellaria",
      "sansa",
      "arya",
      "hound",
      "bran",
      "hodor",
      "jon",
      "sam",
      "tormund",
      "ygritte",
      "daenerys",
      "jorah",
      "missandei",
      "greyWorm",
      "daario",
      "stannis",
      "davos",
      "melisandre",
      "brienne",
      "littlefinger",
      "varys",
    ],
  },
  {
    number: 5,
    title: "The Wars to Come",
    year: "2015",
    blurb: "Faith militant rise in King's Landing. Jon Snow is chosen at the Wall. Daenerys's rule in Meereen is tested. Sansa returns north.",
    characters: [
      "cersei",
      "jaime",
      "tommen",
      "margaery",
      "highSparrow",
      "tyrion",
      "varys",
      "daenerys",
      "jorah",
      "missandei",
      "greyWorm",
      "daario",
      "jon",
      "sam",
      "gilly",
      "stannis",
      "melisandre",
      "davos",
      "sansa",
      "littlefinger",
      "ramsay",
      "roose",
      "theon",
      "arya",
      "jaqen",
      "brienne",
      "olenna",
      "tormund",
    ],
  },
  {
    number: 6,
    title: "The Red Woman",
    year: "2016",
    blurb: "The dead do not stay dead. Alliances shatter in King's Landing, and the North remembers who their king should be.",
    characters: [
      "jon",
      "sansa",
      "davos",
      "melisandre",
      "tormund",
      "brienne",
      "theon",
      "ramsay",
      "daenerys",
      "tyrion",
      "varys",
      "missandei",
      "greyWorm",
      "cersei",
      "jaime",
      "tommen",
      "margaery",
      "highSparrow",
      "olenna",
      "arya",
      "bran",
      "hodor",
      "sam",
      "gilly",
      "euron",
      "yara",
      "littlefinger",
      "qyburn",
    ],
  },
  {
    number: 7,
    title: "Dragonstone",
    year: "2017",
    blurb: "Ice and fire finally meet. Daenerys sails west, the Great War looms, and old houses choose their last loyalties.",
    characters: [
      "daenerys",
      "jon",
      "tyrion",
      "cersei",
      "jaime",
      "sansa",
      "arya",
      "bran",
      "theon",
      "yara",
      "euron",
      "varys",
      "jorah",
      "missandei",
      "greyWorm",
      "davos",
      "brienne",
      "hound",
      "gendry",
      "tormund",
      "sam",
      "gilly",
      "littlefinger",
      "olenna",
      "bronn",
      "qyburn",
      "melisandre",
    ],
  },
  {
    number: 8,
    title: "The Iron Throne",
    year: "2019",
    blurb: "The Great War comes to Winterfell. The last claim to the Iron Throne is decided — and the song of ice and fire ends.",
    characters: [
      "daenerys",
      "jon",
      "sansa",
      "arya",
      "bran",
      "tyrion",
      "cersei",
      "jaime",
      "theon",
      "varys",
      "jorah",
      "missandei",
      "greyWorm",
      "davos",
      "brienne",
      "hound",
      "gendry",
      "tormund",
      "sam",
      "gilly",
      "euron",
      "bronn",
      "qyburn",
      "yara",
    ],
  },
];
